scripts/greaseweazle/tools/seek.py

Some drives won't seek when the 'motor on' signal is not asserted. One such example is my Mitsumi D359T2.

Add option to seek with drive motor on

---

scripts/greaseweazle/tools/util.py

I figured from the posts in #103 that it would be worthwhile to expand the error message a bit.
Output now looks something like this:
```
% ./gw read --drive 0 foo.fdi
** FATAL ERROR:
foo.fdi: Unrecognised file suffix '.fdi' (known suffixes: .adf, .scp, .hfe, .ima, .img, .ipf, .dsk, .raw)
```
If there's some changes you'd like to have (for instance, the error message generation is now the longest line in the file) please let me know.

Present list of supported image types when asking for one that doesn't exist

---

scripts/greaseweazle/tools/util.py

Unless "cylkinders" are some sort of strange unit I've never heard of, that is :smile: The e.g. doesn't really matter but I figured I'd add it in there while I was at it.

Fix typos in help text

---

scripts/greaseweazle/codec/formats.py
scripts/greaseweazle/codec/ibm/fm.py

This is the format used by the Atari 810, commonly used with Atari 800 computers.
I have just a single floppy in this format, and with this patch and Adafruit's generic GW compatible it almost reads.. but consistently has errors in certain sectors.
```
T39.0: IBM FM (17/18 sectors) - 1 sectors missing - Giving up
Cyl-> 0         1         2         3
H. S: 0123456789012345678901234567890123456789
0. 0: X.....X.....X.....X.....X.....X.....X...
0. 1: ........................................
0. 2: ........................................
0. 3: .X.....X.....X.....X.....X.....X.....X..
0. 4: ........................................
0. 5: ........................................
0. 6: ..X.....X.....X.....X.....X.....X.....X.
0. 7: ........................................
0. 8: …
```

Add Atari 90kB format

---

scripts/greaseweazle/tools/clean.py
scripts/greaseweazle/tools/erase.py
scripts/greaseweazle/tools/pin.py
scripts/greaseweazle/tools/read.py
scripts/greaseweazle/tools/rpm.py
scripts/greaseweazle/tools/seek.py
scripts/greaseweazle/tools/util.py
scripts/greaseweazle/tools/write.py
scripts/greaseweazle/usb.py

Hi! For Adafruit, it's my intention to extend the Greasweazle protocol so that it can support Apple II-style floppy drive interfaces. I'm new to Apple II disk reading & preservation so I will have a lot to learn.
Compared to a PC or Shugart interface, there are some notable differences:
* Instead of step & direction, there are 4 "winding activation" signals. The GW-compatible hardware will generate these outputs on hardware-defined pins.
* While the track spacing is the same as a PC "double density" disk, the read/write head can be positioned 1/4 as finely as a single track spacing. Apparently, this is used in copy protected Apple II software, similar to fat/half tracks in Commodore 64, just worse.
* There is no "track 0" sensor, instead the "bang your head into a wall" algorithm is used. …

Add Apple floppy types

---

src/greaseweazle/image/hdm.py
src/greaseweazle/tools/util.py

Technically this extension belongs to a whole series of formats:
https://github.com/keirf/FlashFloppy/issues/198
However, I have only been able to find HDM, so I can't verify that
the others are correct. As a result I'm only adding HDM.

Add HDM image format for NEC PC-98.

---

src/greaseweazle/codec/formats.py
src/greaseweazle/codec/ibm/mfm.py
src/greaseweazle/image/dim.py
src/greaseweazle/tools/write.py

This also adds the 2HS format, and adds a mechanism for the image
to return a string format name, which overrides the CLI provided
format.

Add 2HS format support to DIM image format.

---

src/greaseweazle/image/d88.py
src/greaseweazle/tools/util.py

This is a minimum viable D88 reader, which only supports 1.2MB HD
disks (e.g. NEC PC-98). FM sectors, FDC error codes, DDAM markers,
and extra data past 128<<n is currently unsupported.
Mixed sector sizes and arbitrary c/h/r values are supported.
Verification may not work as intended with duplicate c/h/r values.

Add initial D88 image support.

---

src/greaseweazle/image/d88.py

These match fluxengine, however ideally they would be replaced
with computation of the optimal gap.

Add basic gap3 heuristics to D88 reader.

---

src/greaseweazle/codec/formats.py
src/greaseweazle/codec/ibm/mfm.py
src/greaseweazle/image/d88.py
src/greaseweazle/image/dim.py
src/greaseweazle/image/fdi.py
src/greaseweazle/image/hdm.py
src/greaseweazle/image/xdf.py

This aligns them with NEC and other common Japanese literature.

Rename pc98.dd and pc98.hd formats.

---

src/greaseweazle/data/diskdefs.cfg

The Osborne 1 has two disk formats, on it's 5.25 single sided, 40-track drives:
"Single Density" (non-upgraded models):
FM, 125kbps, 10 sectors per track, 256 bytes per sector
"Double Density" (an additional upgrade board):
MFM, 250 kbps, 5 sectors per track, 1024 bytes per sector
I can only check occ1.sd, but I can confirm that it works fine.
I can gw read with and without the format, and the .img from gw matches the output of disk-analyse. Writing it back with gw write --format results in a functional copy of the disk.
```
gw read --drive=1 --tracks="c=0-39:h=0" --format occ1.sd help-$(date +%s).img
Reading c=0-39:h=0 revs=2
Format occ1.sd
T0.0: IBM FM (10/10 sectors) from Raw Flux (74512 flux in 400.91ms)
T1.0: IBM FM (10/10 sectors) from Raw Flux (76247 flux in 400.81ms)
T2.0: IBM FM …
```

diskdefs: Add Osborne 1 single and double density formats

---

src/greaseweazle/data/diskdefs.cfg

This is a slightly unusual format (very similar to rx01) used
by N88-Basic disks for the NEC PC-98.
There is an equivalent DD format that I might add once I am able
to test it.

Add pc98.n88basic.hd format

---

src/greaseweazle/data/diskdefs.cfg

Quorum is Russian ZX Spectrum clone from 90s, which used CP/M-80 instead of TR-DOS.
AFAIK The same disk format was also used in "Korvet" Soviet CP/M computer, but I have no "Korvet" disks to test.

Add definition for Quorum ZX Spectrum clone CP/M disks

---

src/greaseweazle/data/diskdefs.cfg

BBC Micros had the possibility for 80T disks that were FM formatted. The drives typically have a 40/80T switch for this. Typically this would be called DDFS by most manufacturers, although Acorn's 1770 DFS falls into this category.
This commit adds a profile to read disks when hooked up to a BBC Micro disk drive in 80T mode.
Note that there is no DS option as interleaved DS was not really a thing on BBC Micros, sides were given separate drive numbers.

Add support for BBC DDFS disks/drives

---

src/greaseweazle/data/diskdefs.cfg

Reverts keirf/greaseweazle#427
DDFS was a double density DFS, deployed by Watford (and others) with their
1770 disk interface - it's an MFM format, and could be 40 or 80 track,
single or double sided (not interleaved). 80 track FM was simply 80 track
DFS format (again, single or double sided not interleaved). Check here for
more detail: https://stardot.org.uk/forums/viewtopic.php?p=390348#p390348

Revert "Add support for BBC DDFS disks/drives"

---

src/greaseweazle/tools/util.py

If the USB device's product string contains "gw-compat" (case insensitive), it will be treated as a device greaseweazle can use, albeit at a lower priority than a genuine Greaseweazle.
Together with a 1-liner change in Adafruit_Floppy's compatible firmware, this allows `gw` commands to work with that firmware without specifying a --device to every command.
If you'd prefer to accomplish this in a different way, I'm open to your suggestions. For instance, I think Adafruit could allocate a unique VID:PID for an Adafruit product running this sketch. This might also be easier better for compatibility with @davidgiven's fluxengine, which doesn't currently look at product strings, just VID:PID pairs, when deciding device compatibility. (however, it might have consequences within the Arduino …

score_port: Accept "gw-compat" products

---

src/greaseweazle/data/diskdefs.cfg

This adds diskdefs  for various Epson QX-10 formats I have seen used while imaging disks for that system.

diskdefs: Add support for Epson QX-10 disk formats

---

src/greaseweazle/data/diskdefs.cfg

I added definitions for all the floppy disk formats that were released  by Thomson along the history of the MO5, MO6, TO7, TO7/70, TO8, TO8D, TO9 & TO9+ computers.
Ideally, this would be complemented by support for .fd files (same as .img but with all tracks and sectors of side 0 before all tracks/sectors of side 1).

Add thomson format definitions

---

scripts/misc/artifact.py
src/greaseweazle/codec/codec.py
src/greaseweazle/tools/util.py

When running `gw --help` for the first time under Python 3.12, I get a bunch of warnings:
```
.../src/greaseweazle/tools/util.py:103: SyntaxWarning: invalid escape sequence '\d'
m = re.match('(\d*\.\d+|\d+)rpm', arg)
.../src/greaseweazle/tools/util.py:106: SyntaxWarning: invalid escape sequence '\d'
m = re.match('(\d*\.\d+|\d+)ms', arg)
.../src/greaseweazle/tools/util.py:109: SyntaxWarning: invalid escape sequence '\d'
m = re.match('(\d*\.\d+|\d+)us', arg)
.../src/greaseweazle/tools/util.py:112: SyntaxWarning: invalid escape sequence '\d'
m = re.match('(\d*\.\d+|\d+)ns', arg)
.../src/greaseweazle/tools/util.py:115: SyntaxWarning: invalid escape sequence '\d'
m = re.match('(\d*\.\d+|\d+)scp', arg)
.../src/greaseweazle/tools/util.py:193: SyntaxWarning: invalid escape sequence '\d'
m = …
```

Use raw strings for regexes; fixes SyntaxWarning: invalid escape sequence

---

src/greaseweazle/tools/read.py

Really small QoL improvement: when reading raw flux with a format applied, tracks outside the range of that format would not display the raw flux summary.
This is still useful information because we're still getting raw flux even if it doesn't match the format, and we're probably intentionally reading these extra tracks because they might contain extra data (e.g. for copy protection).

Print raw flux summary even if no format conversion was applied for out of range tracks

---

src/greaseweazle/data/diskdefs_zx.cfg

Standardized the naming convention for disk formats across various ZX Spectrum and compatible systems:
Replaced .dsdd suffix with .ds80 for all double-sided, 80-cylinder disk configurations to improve clarity and consistency.
Replaced .sssd suffix with .ss40 for all single-sided, 40-cylinder disk configurations to align with uniform terminology.
This update ensures a more intuitive and standardized configuration file for better readability and maintainability across supported platforms.

Update diskdefs_zx.cfg to standardize ZX Spectrum disk format definitions.

---

src/greaseweazle/tools/util.py
src/greaseweazle/tools/write.py

When you run `gw write --help`, the help contains `--precomp=PRECOMP` but `PRECOMP` is not described later. Since value of this parameter is difficult to guess, this pull request adds the missing PRECOMP description into gw write. The precompensation information was taken from https://github.com/keirf/greaseweazle/wiki/Write-Precompensation.

Add PRECOMP documentation for gw write
